---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    prereq_stack_name: semaphore-cd-prereqs
    app_stack_name: semaphore-cd-app
    aws_region: eu-west-1
    bucket_name: "semapore-cd-releases"
  tasks:
    - name: Provision Pre-req stack
      cloudformation:
        state: present
        stack_name: "{{ prereq_stack_name }}"
        region: "{{ aws_region }}"
        disable_rollback: true
        template: "cloudformation/prereqs.json"
        template_parameters:
          Name: "{{ bucket_name }}"
      register: prereqs

    - name: Generate artifact hash
      command: "./script/release-tag"
      changed_when: False
      register: artifact_hash

    - name: Push Image to ECR
      command: "make push UPSTREAM={{ prereqs.stack_outputs.AccountID }}.dkr.ecr.{{ aws_region }}.amazonaws.com/semaphore-cd:{{ artifact_hash.stdout }}"
      changed_when: False
