---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    aws_region: eu-west-1
    app_name: "semaphore-cd"
    prereq_stack_name: "{{ app_name }}-prereqs"
    app_stack_name: "{{ app_name }}-main"
    bucket_name: "{{ app_name }}-releases"
  tasks:
    - name: Provision Pre-req stack
      cloudformation:
        state: present
        stack_name: "{{ prereq_stack_name }}"
        region: "{{ aws_region }}"
        disable_rollback: true
        template: "cloudformation/prereqs.json"
        template_parameters:
          BucketName: "{{ bucket_name }}"
          RepositoryName: "{{ app_name }}"
      register: prereqs

    - name: Generate artifact hash
      command: "./script/release-tag"
      changed_when: False
      register: artifact_hash

    - name: Push Image to ECR
      command: "make push UPSTREAM={{ prereqs.stack_outputs.Repository }}:{{ artifact_hash.stdout }}"
      changed_when: False
